default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  pool: 5

development:
  <<: *default
  database: blog_app_db

test:
  <<: *default
  database: blog_app_db_test
